version: '3'
services:
  # Dịch vụ Node.js
  nodejs-app:
    build:
      context: ./NodeJS
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/my_database
    networks:
      - app-network

  # Dịch vụ React.js
  reactjs-app:
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-app
    networks:
      - app-network

  # Dịch vụ MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
